siteTitle: Site Title
tagLine: Attorneys and Counselors
themePath: engage
themeHead: engage/head.html
themeHeader: engage/header.html
themeFooter: engage/footer.html
themeSiteNav: engage/siteNav.html

collections:
  attorneys:
    output: true
  locations:
    output: true
