name: 089-fotograf.de
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 auto_ids: true
 # parse_block_html: true
repository: 'rendrap/r24'
plugins:
  # - jekyll-feed
  # - jekyll-paginate
keep_files: [images]
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", ".jekyll-metadata","uru_rt.exe","source-code","fonts","uru*","assets/img/PSD","assets/scss-temp/"]
collections:
  practiceLitigation:
    output: true
    permalink: /practice_areas/:name
  practiceTransaction:
    output: true
    permalink: /practice_areas/:name


defaults:
  - scope:
      path: ""
      type: "practiceLitigation"
    values:
      layout: "default"
      nav-current: practice_areas/
  - scope:
      path: ""
      type: "practiceTransaction"
    values:
      layout: "default"
      nav-current: practice_areas/