name: 089-fotograf.de
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 auto_ids: true
 # parse_block_html: true
repository: 'rendrap/r24'
plugins:
  # - jekyll-feed
  # - jekyll-paginate
keep_files: [images]
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", ".jekyll-metadata","uru_rt.exe","source-code","fonts","uru*","assets/img/PSD"]
collections:
  content:
    output: true