name: http://www.jonesdavis.com
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 auto_ids: true
 # parse_block_html: true
repository: 'rendrap/JonesDaviscom'
plugins:
  # - jekyll-feed
  # - jekyll-paginate
# keep_files: [images]
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", ".jekyll-metadata","uru_rt.exe","source-code","fonts","uru*","assets/img/PSD","assets/scss-temp/"]
collections:
  practiceLitigation:
    output: true
    permalink: /practice_areas/litigation/:name
  practiceTransaction:
    output: true
    permalink: /practice_areas/transaction/:name
  practiceChurch:
    output: true
    permalink: /practice_areas/church/:name
  attorneys:
    output: true
    permalink: /attorneys/:name
  locations:


defaults:
  - scope:
      path: ""
      type: "practiceLitigation"
    values:
      layout: "default"
      nav-current: practice_areas/
  - scope:
      path: ""
      type: "practiceTransaction"
    values:
      layout: "default"
      nav-current: practice_areas/
  - scope:
      path: ""
      type: "practiceChurch"
    values:
      layout: "default"
      nav-current: practice_areas/
  - scope:
      path: ""
      type: "attorneys"
    values:
      layout: "default"
      nav-current: attorneys/